In [14]:
import numpy as np  ## ipmorting numpy library here...

a = np.array([1,2,4,6,78,8,2])
print("Simply print numpy array.\n",a)
## printing numpy array...

Simply print numpy array.
 [ 1  2  4  6 78  8  2]


In [24]:
## perfroming simple arithematic operations on numpy array...
print("This is addition of array with number.\n",a + 4)      
## adding by number... 

This is addition of array with number.
 [ 5  6  8 10 82 12  6]


In [25]:
## perfroming simple arithematic operations on numpy array...
print("This is subtraction of array with number.\n",a - -1)     
  ## subtraction by number...

This is subtraction of array with number.
 [ 2  3  5  7 79  9  3]


In [26]:
## perfroming simple arithematic operations on numpy array...
print("This is multiplication of array with number.\n",a * 4)  
  ## multiplication by number...

This is multiplication of array with number.
 [  4   8  16  24 312  32   8]


In [30]:
## perfroming simple arithematic operations on numpy array...
print("This is division of array with number.\n",a / 3)       
  ## division by number... 

This is division of array with number.
 [ 0.33333333  0.66666667  1.33333333  2.         26.          2.66666667
  0.66666667]


In [31]:
## operation with arrays
print("This is addition of array itself.\n",a + a)        
 ## this will add array itself...

This is addition of array itself.
 [  2   4   8  12 156  16   4]


In [32]:
print("This is subtraction of array itself.\n",a - a)        
## this will subtract array itself...

This is subtraction of array itself.
 [0 0 0 0 0 0 0]


In [33]:
print("This is multiplication of array itself.\n",a * a)       
  ## this will multiply array itself...

This is multiplication of array itself.
 [   1    4   16   36 6084   64    4]


In [37]:
print("This is division of array itself.\n",a / a)      
   ## this will divide array itself...

This is division of array itself.
 [1. 1. 1. 1. 1. 1. 1.]
